### ISSUE TITLE
不管是新安装还是从这里clone，都是出错的

### ISSUE THREAD

**Issue by jeanbi** [lufficc/Xblog#13]
不管是使用composer create-project lufficc/xblog PrjName，还是clone这个版本的代码，到最后都是出现这个错误，啥情况？

```
> php artisan optimize
PHP Parse error:  parse error in /Users/user/Works/Xblog/vendor/laravel/scout/src/Console/FlushCommand.php on line 32

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  parse error 
```
我使用composer create-project laravel/laravel PrjName是可以正常创建项目，并运行起来。说明我的环境是正常的。

**Comment by jeanbi** [comment]
运行起来了，似乎是网络问题，有相关依赖没有更新下来。
有个建议，当然放在这里可能不合适。就是，可不可以把首页弄掉？直接打开就是博客首页，现在这个首页感觉很没必要的一个设定呢。

**Comment by lufficc** [comment]
这个简单web.php的路由你可以随便移动，不更改它的名称就行，就不会出错。把`\blog`改成`\`即可
