### ISSUE TITLE
如何设置管理员账号

### ISSUE THREAD

**Issue by 839891627** [lufficc/Xblog#16]
> 首先注册一个用户, 只有ID为1的用户是管理员。登陆之后进入后台 > 设置。

这个没懂啊，前台用户是users表，后台用户呢？
没看到后台登录的窗口

**Comment by lufficc** [comment]
后台用户前台用户一个表。。。你先不要db:seed，先注册你自己的用户，第一个用户自动是管理员，下来菜单会显示后台入口

**Comment by 839891627** [comment]
嗯  弄好了。谢谢啊

**Comment by 839891627** [comment]
你的这个项目真不错。看一些教程都是零零碎碎的，这个刚好拿来系统学习。赞
