### ISSUE TITLE
cache为什么使用contract而不是facade？

### ISSUE THREAD

**Issue by 839891627** [lufficc/Xblog#26]
看laravel的文档，还是没怎么理解，说都可以使用。
但是xblog里面config使用了facade，cache使用了contract
1. 为什么没有统一？
2. 是不是有什么最佳实践呀？

**Comment by lufficc** [comment]
按照我的理解：
如果是可变的选项，去不同的缓存驱动，文件存储驱动，用contract,
如果是为了省事，或者是全局的单例。
