### ISSUE TITLE
谁能提交一个显示notifications的界面？路由为/notifications

### ISSUE THREAD

**Issue by lufficc** [lufficc/Xblog#28]

**Comment by lufficc** [comment]
参考https://lufficc.com/notifications

**Comment by mngogo** [comment]
I can have a try,

**Comment by lufficc** [comment]
You can pull the newest repository, then add it.

**Comment by lucasloo** [comment]
你好我按照着你的评论查看页面做了一个notifications的展示页面。但是有两个问题：
* 这个notifications页面应该从哪里跳转进去？
* 这个notifications不是一个resource，应该怎么处理改成已读状态呢？

**Comment by lufficc** [comment]
竟然还有人回应，: ) 感觉这里不错>
![image](https://cloud.githubusercontent.com/assets/20706332/23688276/80cb592a-03ee-11e7-8643-9383bf7b2cfb.png)
