### ISSUE TITLE
关于composer update出现的错误

### ISSUE THREAD

**Issue by bibbyee** [lufficc/Xblog#29]
按照文档配置执行composer update时出现错误
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Console\Application::starting()
Script php artisan optimize handling the post-update-cmd event returned with an error
  [RuntimeException]
  Error Output:
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--
autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [

**应该改为composer update --no-scripts**

**Comment by lufficc** [comment]
应该是你的环境问题吧，我`composer update`没问题
