### ISSUE TITLE
header.blade.php 获取未读消息数报错

### ISSUE THREAD

**Issue by igo9go** [lufficc/Xblog#31]
![image](https://cloud.githubusercontent.com/assets/11486721/20739208/b1a175fe-b6f3-11e6-9141-3a7fd788d7a7.png)

![image](https://cloud.githubusercontent.com/assets/11486721/20739183/86be2896-b6f3-11e6-8c14-cc36d3d5a59b.png)

**Comment by lufficc** [comment]
把 `config\database.php` mysql 'strict' => true 改为 `false`
