### ISSUE TITLE
调用资源文件路径错误

### ISSUE THREAD

**Issue by viosey** [lufficc/Xblog#37]
例如访问的是：`http://viosey.dev/xblog/public`
资源所在路径：`http://viosey.dev/xblog/public/build/css/home.css`
但是调用的是：`http://viosey.dev/build/css/home.css`

**Comment by viosey** [comment]
虽然设置了直接解析到 `http://viosey.dev/xblog/public` 可以解决，但是有无其他方法？

**Comment by lufficc** [comment]
你的本地开发环境是什么？

**Comment by viosey** [comment]
OS X + MAMP

**Comment by lufficc** [comment]
MAMP是个坑。。。

**Comment by lufficc** [comment]
1. make sure you set the document root to the /public directory in your laravel installation.
2. make sure you have enabled rewrite module in your mamp. Checkout http://stackoverflow.com/questions/7670561/how-to-get-htaccess-to-work-on-mamp

具体的看看这里：http://laravel.io/forum/05-02-2014-laravel-why-cant-you-play-nice-with-mamp
建议HomeStead开发
