### ISSUE TITLE
其实我想知道这个博客怎么用？

### ISSUE THREAD

**Issue by SmallFatCYW** [lufficc/Xblog#46]
表示不会PHP，只是看到这个博客很酷就想尝试，但是扔进空间后，访问是403，所以如何安装呢？谢谢啊

**Comment by lufficc** [comment]
[如何安装Xblog](https://lufficc.com/blog/how-to-install-my-blog) 这是我写的教程， 不懂的可以在下面留言

**Comment by SmallFatCYW** [comment]
en,谢谢，知道了:D
