### ISSUE TITLE
github redirect 填写回调url 是否是填写 application 上填写回调url？

### ISSUE THREAD

**Issue by Twitchboy** [lufficc/Xblog#53]
github redirect 填写回调url 是否是填写 application 上填写回调url？

**Comment by lufficc** [comment]
![image](https://cloud.githubusercontent.com/assets/20706332/23329952/7ecfe3b6-fb7e-11e6-8d62-c3bd10f2d595.png)

**Comment by Twitchboy** [comment]
嗯，填写的自己的域名，不过设置 好giithub client id 、secret； GITHUB_REDIRECT （填写的是 https://github.com/login/oauth/authorize ）这里配置有错吗，使用github登录 访问的是一个白页 没有跳转到绑定应用上！

**Comment by lufficc** [comment]
填写你自己网线的 URL 啊，你自己回调地址

**Comment by Twitchboy** [comment]
![Uploading 图片.png…]()
换成了自己设置的回调url 还是跳白页面！

**Comment by lufficc** [comment]
你的重定向没处理好吧？
