### ISSUE TITLE
 为什么这里引入css,js要这样判断

### ISSUE THREAD

**Issue by igo9go** [lufficc/Xblog#6]
![](http://oc9orpe44.bkt.clouddn.com/16-10-8/63885752.jpg)

这里不是应该去判断是开发环境还是生产环境吗，开发环境就没必要引入打包后的css.

**Comment by lufficc** [comment]
这里是为了统一，你在本地时，不用在后台设置地址，这样会加载本地的脚本。线上环境因为js较大，你可以上传到七牛云或者其他cdn做加速。
优先使用加载cdn~~
