### ISSUE TITLE
Create localization to translate for other languages

### ISSUE THREAD

**Issue by lex111** [lufficc/Xblog#61]
Now all text messages in views are written in Chinese, which makes it difficult to use the application in other languages. If all of them were defined in language files, it was convenient to manage the translation of phrases. In Laravel for this purpose there are means of [localization](https://laravel.com/docs/5.4/localization), can use them?

**Comment by lufficc** [comment]
Well, thanks a lot for your nice suggestion. I will make it done next version.

**Comment by isbkch** [comment]
Your blogging platform seems to be exactly what I am looking for. The language is the only barrier though, it would be super nice to open it for translation

**Comment by joekabucho** [comment]
i translated most parts of it...
