### ISSUE TITLE
自带评论的头像不显示

### ISSUE THREAD

**Issue by wwwxmu** [lufficc/Xblog#63]
如图
![image](https://cloud.githubusercontent.com/assets/12303465/23822046/fb959160-067e-11e7-99dc-dc1d3e9eb57d.png)

**Comment by lufficc** [comment]
`.env`  的这个东西每填：
![image](https://cloud.githubusercontent.com/assets/20706332/23822485/4d31f4ec-0688-11e7-88a9-9093ffac6433.png)

**Comment by wwwxmu** [comment]
这个填过了。。。
但是头像怎么会跟七牛的路径有关，我七牛上又没有图片。。。难道源代码里面没有一个头像库？

**Comment by hongweihua** [comment]
要有一个默认的头像图片
