### ISSUE TITLE
Themes 文件夹为什么要放 Controllers？

### ISSUE THREAD

**Issue by airycanon** [lufficc/Xblog#66]
刚刚学习了 dev 分支的代码，按我的理解，themes 中应该只包含 views 和 assets，为什么把 Controllers 也放进去，是考虑了不同的主题路由和 Controller 的实现也可能不同么，这样对于想要自定义主题的使用者是不是不太友好？

**Comment by lufficc** [comment]
因为即使框架考虑再多的情况，也不可能涵盖所有。 `Controller ` 只是为主题开发者提供更多的可扩展性。事实上，你也可以自定义自己的路由。

但是，如果只是简单的样式主题，即只是更改了样式文件，主题完全可以使用默认的路由和默认的数据绑定（默认路由：[common.php](https://github.com/lufficc/Xblog/blob/dev/routes/common.php)）。默认的数据绑定 [XblogController.php](https://github.com/lufficc/Xblog/blob/dev/app/Http/Controllers/XblogController.php)。但是默认的数据不一定符合所有要求，你也可以使用全局函数来获取数据：[data.php](https://github.com/lufficc/Xblog/blob/dev/app/Helpers/data.php)

主题处于 beta 阶段，成熟之后我会详细介绍。
