### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by vatezj** [lufficc/Xblog#68]
Call to undefined method Illuminate\Session\Store::set()
报错了 使用github登录时报错了

**Comment by lufficc** [comment]
https://github.com/laravel/socialite/pull/197

[socialite](https://github.com/laravel/socialite) 源码没兼容

**Comment by vatezj** [comment]
将socialite AbstractProvider 143 行的session()->set() 改错 session()->put()就行了

**Comment by lufficc** [comment]
是的
