### ISSUE TITLE
普及一下scout的algoliasearch和elasticsearch二个引擎的使用方法吧

### ISSUE THREAD

**Issue by igo9go** [lufficc/Xblog#7]

**Comment by lufficc** [comment]
原理很简单，algolia就是把你的数据同步到他的数据库，搜索的时候请求它的api，它返回搜索数据。如果不用异步的话，可能会很慢。你可以不使用，不影响你的程序的。
视频教程：
https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/15
