### ISSUE TITLE
How to use emojis in posts?

### ISSUE THREAD

**Issue by hanzhaogit** [lufficc/Xblog#72]
Hi, When emojis appears in the post will save fails, it returns http 500.
I had changed all MySQL encoding to utf8mb4. I use mysql-cli to change the `html_content` value, but the emoji became `?` in the webpage.
So tell me how can I insert emojis to post please?

------
您好，请问怎么在文章中使用emojis表情呢？我感觉保存时报错是当前代码只支持utf-8编码的原因吧？那我也可以在保存文章后手动去数据库插入表情，但是展示的时候表情都变成了`?`，请问您我怎么做能让它正常显示呢？

**Comment by lufficc** [comment]
MySql 数据库的默认编码是 utf-8，不支持emojis，需要改为 utf8mb4

**Comment by hanzhaogit** [comment]
非常感谢您的回复，确实就是这个编码的原因。后来我解决掉了，忘了这边儿的 issue 了！

1.  一方面，要将MySQL 数据库的编码改为 utf8mb4
2. 此外，还需要更改 /config/datebase.php中connections.mysql 的 charset及collation参数值。

再次感谢！
