### ISSUE TITLE
后台个人中心修改配置前台不生效问题

### ISSUE THREAD

**Issue by DBING** [lufficc/Xblog#79]
后台个人中心修改github地址与微博地址等~~前台不能生效

**Comment by lufficc** [comment]
忘了，这个是在这儿配置的 https://github.com/lufficc/Xblog/blob/master/config/social.php#L10-L25

**Comment by DBING** [comment]
3克油，忘记来GitHub上查看了，debug跟踪代码找到了是social.php这个文件～:)
