### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by yuri25** [lufficc/Xblog#8]
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

**Comment by yuri25** [comment]
Script php artisan optimize handling the post-update-cmd event returned with error code 255

**Comment by lufficc** [comment]
I haven't encountered this problem. Maybe you can re-clone this project can try again.I have optimized this project just now.

**Comment by yuri25** [comment]
I'm sorry I have php v PHP 5.6.23 :(   
Perhaps the cause of the error, you can close issue.

**Comment by lufficc** [comment]
sure,php should > 5.6.4
