### ISSUE TITLE
通知系统好像有点问题  自己回复还是会通知给自己

### ISSUE THREAD

**Issue by hongweihua** [lufficc/Xblog#87]

**Comment by jianwoo** [comment]
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `ips` where `ips`.`id` = 127.0.0.1 limit 1)
Previous exceptions
SQLSTATE[HY000] [2002] Connection refused (2002)
SQLSTATE[HY000] [2002] Connection refused (2002)

**Comment by lufficc** [comment]
This is a bug, I'll fix it laterly.
