### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by jianwoo** [lufficc/Xblog#88]
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `ips` where `ips`.`id` = 127.0.0.1 limit 1)
Previous exceptions
SQLSTATE[HY000] [2002] Connection refused (2002)
SQLSTATE[HY000] [2002] Connection refused (2002)

**Comment by lufficc** [comment]
Maybe DB config is not correct?
