### ISSUE TITLE
CacheServiceProvider.php 的绑定

### ISSUE THREAD

**Issue by yangzhipeng** [lufficc/Xblog#89]
$this->app->bind('XblogCache', function ($app) {
            if (config('cache.enable') == 'true') {
                return new Cacheable();
            } else {
                return new NoCache();
            }
        });

请问这里的XblogCache是对应的自定义Facade的XblogConfig？
public static function getFacadeAccessor()
    {
        return 'XblogConfig';
    }

**Comment by lufficc** [comment]
是的，这样就可以全局访问 `XblogConfi` 了

**Comment by yangzhipeng** [comment]
@lufficc  好的 谢谢
