### ISSUE TITLE
页面加载资源路径错误

### ISSUE THREAD

**Issue by fhefh2015** [lufficc/Xblog#9]
elixir函数，默认加载目录是build， 但是elixir配合gulp生成的资源路径目录是public
所有的页面都加载的是：
```
<link href="/build/css/app-e41eea74a5.css" rel="stylesheet">
<script src="/build/js/app-1d1f1b0983.js"></script>
```

![2016-10-10_11-45-44](https://cloud.githubusercontent.com/assets/14891797/19226555/2ca27ccc-8edf-11e6-8eb8-b1d098856fd2.png)

![2016-10-10_11-46-48](https://cloud.githubusercontent.com/assets/14891797/19226565/446c8a64-8edf-11e6-96dc-a4645a08f3f4.png)

**Comment by lufficc** [comment]
项目根目录下运行gulp 或者gulp --production 即可[需要安装node.js]

**Comment by fhefh2015** [comment]
@lufficc 谢谢
